### ISSUE TITLE
图像上传后显示404的问题

### ISSUE THREAD

**Issue by W3INFO** [ruby-china/homeland-docker#13]
开启了https后，然后测试上传头像，完事之后，看返回的头像是404
![image](https://cloud.githubusercontent.com/assets/17700488/21303542/f6f5a9e4-c5f9-11e6-9b8c-6ca92f54653f.png)

nginx log
`[error] 8#8: *38 open() "/usr/share/nginx/html/_img/uploads/user/avatar/1.jpg!sm" failed (2: No such file or directory)`

**Comment by huacnlee** [comment]
配置看起来不对，你不要用本地文件存储好了，你手工配置本来就已经够复杂的了，直接用 Aliyun OSS 或 UpYun 好了
