### ISSUE TITLE
脚本失效了。404

### ISSUE THREAD

**Issue by XedGo** [ruby-china/homeland-docker#14]
curl -sSL https://git.io/vPALl | bash

**Comment by gaga5lala** [comment]
兩天前的 commit https://github.com/ruby-china/homeland-docker/commit/081f36d1a4260d5947a93c8a6d0d92f33f3f5466 拿掉 `scripts/install-packages` 後沒有更新 base/Dockerfile https://github.com/ruby-china/homeland-docker/blob/master/images/base/Dockerfile#L43

**Comment by XedGo** [comment]
@gaga5lala    这样啊~~  我找到了原来的部署脚本，继续使用应该没有影响吧

**Comment by huacnlee** [comment]
修好了
