### ISSUE TITLE
Nginx的BUG

### ISSUE THREAD

**Issue by RTO-Login** [ruby-china/homeland-docker#19]
在非docker模式下部署HTTPS，使用腾讯系应用的内置浏览器是可以访问的，例如：ruby-china.org

在docker模式下部署HTTPS，使用腾讯系系应用的内置浏览器是不可以访问的，抓包看了半天没弄出个所以然

不可能是TX的问题，因为ruby-china.org可以访问，docker模式下却不行（用https），建议开发者测试一下

**Comment by huacnlee** [comment]
Nginx 配置一调整，问题已修复，更新一下
