### ISSUE TITLE
[error] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by gogobody** [ruby-china/homeland-docker#52]
在执行sudo make install_ssl遇到如下错误：
`docker-compose run web ash -c '/root/.acme.sh/acme.sh --installcert --home /home/app/ssl -d $cert_domain --keypath /home/app/ssl/homeland.key --fullchainpath /home/app/ssl/homeland.crt --reloadcmd "nginx -s reload"'
Starting homeland_elasticsearch ... done
Starting homeland_postgresql    ... done
Starting homeland_redis         ... done
Starting homeland_worker        ... done
Starting homeland_app           ... done
Starting homeland_app_backup    ... done
[Fri Apr  3 10:49:20 UTC 2020] Installing key to:/home/app/ssl/homeland.key
[Fri Apr  3 10:49:20 UTC 2020] Installing full chain to:/home/app/ssl/homeland.crt
[Fri Apr  3 10:49:20 UTC 2020] Run reload cmd: nginx -s reload
nginx: [error] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
[Fri Apr  3 10:49:20 UTC 2020] Reload error for :
make: *** [install_ssl] Error 1`

**Comment by yibum** [comment]
这一步其实已经成功申请并安装完SSL相关的证书，只是在`nginx -s reload`的时候出错。

只要修改配置`https=true`并且`sudo make restart`重启web服务即可，此时`nginx`相关服务会重新加载配置并启用SSL。

如果要完全修复这个错误，可能要修改Dockerfile，添加`RUN mkdir -p /run/nginx`。
