### ISSUE TITLE
homeland_elasticsearch

### ISSUE THREAD

**Issue by differs** [ruby-china/homeland-docker#54]
elasticsearch 不能正常启动哦。
Starting homeland_elasticsearch ... done
=> Booting Homeland
=> Plugins: 
rake aborted!
Faraday::ConnectionFailed: Failed to open TCP connection to elasticsearch:9200 (getaddrinfo: Name does not resolve)
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:152:in `request_via_request_method'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:137:in `request_with_wrapped_block'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/transport/http/faraday.rb:27:in `block in perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/transport/base.rb:274:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/client.rb:163:in `perform_request'

**Comment by huacnlee** [comment]
更新 homeland-docker 以及 homeland 的 Docker Image, ElasticSearch 已经去掉了
